### ISSUE TITLE
TypeError: path.join is not a function

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-github-action#7]
### Describe the problem you discovered

```
Creating file structure and compress content...
TypeError: path.join is not a function
    at file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/file.js:65:3[8](https://github.com/archethic-foundation/archethic-website/actions/runs/4077101091/jobs/7025690781#step:3:9)
    at Array.reduce (<anonymous>)
    at getFilters (file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/file.js:64:21)
    at handleDirectory (file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/file.js:31:15)
    at getFolderFiles (file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/file.js:14:5)
    at handler (file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/action.js:36:3)
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/archethic-foundation/archethic-website/actions/runs/4077101091/jobs/7025690781#step:3:10)6:5)
    at async file:///home/runner/work/_actions/archethic-foundation/aeweb-github-action/v1.5.3/index.js:6:3
```

**Comment by samuelmanzanera** [comment]
I didn't get this issue.
I have created a repo to test the action. Here is the output of the latest build:
https://github.com/samuelmanzanera/test_aeweb_actions/actions/runs/4077939674/jobs/7027554082
